name: 'Terraform'

on:
    push:
        branches:
            - main
            - feature/*
    pull_request:
    workflow_dispatch:
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.TERRAFORM_AWS_DEFAULT_REGION }}
    TF_VAR_profile: terraform-infra-user

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TERRAFORM_AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: |
          cd ./terraform/nginx-ec2/1_ec2
          terraform init

      - name: Save SSH key to file
        run: |
          echo "${{ secrets.TERRAFORM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Terraform Plan
        run: |
          cd ./terraform/nginx-ec2/1_ec2
          terraform plan -var-file=../_env_config/dev.tfvars -out create.plan

      - name: Terraform Apply
        run: |
          cd ./terraform/nginx-ec2/1_ec2 
          terraform apply "create.plan" -auto-approve
          