name: 'Terraform'

on:
    push:
        branches:
            - main
            - feature/*
    pull_request:
    workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TERRAFORM_AWS_DEFAULT_REGION }}
            
      - name: ec2 dev
        run: cd ${{ github.repository }}/terraform/nginx-ec2/1_ec2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=../_env_config/dev.tfvars -out create.plan

      - name: Terraform Apply
        run: terraform apply "create.plan" -auto-approve
        env:
          TF_VAR_profile: terraform-infra-user